"""add avatar_url to doctors

Revision ID: 3c5a170017bb
Revises: 0004_staff_role_alignment
Create Date: 2026-09-27 23:34:55.548108
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c5a170017bb'
down_revision: Union[str, None] = '0004_staff_role_alignment'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('doctors', sa.Column('gender', sa.String(length=16), nullable=True))
    op.add_column('doctors', sa.Column('title', sa.String(length=64), nullable=True))
    op.add_column('doctors', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'date_of_birth')
    op.drop_column('doctors', 'title')
    op.drop_column('doctors', 'gender')
    op.drop_column('doctors', 'avatar_url')
    # ### end Alembic commands ###
