"""Add missing fields to Service model

Revision ID: 44837e30b196
Revises: 3c5a170017bb
Create Date: 2026-09-28 00:21:19.155471
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '44837e30b196'
down_revision: Union[str, None] = '3c5a170017bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('services', sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('services', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('services', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('services', sa.Column('patient_count', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('satisfaction_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'satisfaction_rate')
    op.drop_column('services', 'patient_count')
    op.drop_column('services', 'features')
    op.drop_column('services', 'category')
    op.drop_column('services', 'original_price')
    op.drop_column('services', 'price')
    # ### end Alembic commands ###
