-- Gán lại chuyên khoa chính (primary_specialty_code/name) cho disease_triage: dữ liệu crawl gán gần như ngẫu nhiên
-- (vd Ù tai, Vô sinh nữ → Tim mạch; Bạch biến → Tiêu hóa; Cận thị → Thần kinh; 71 bệnh mã CO_XUONG_KHOP không khớp mã triage).
-- Luật từ khóa theo tên bệnh + gán tay (78 ca); bảng duyệt: reports/triage_eval/disease_specialty_review.csv.
-- Tên chuyên khoa dùng đúng tên hiển thị của language_service để tìm được bác sĩ trong danh mục specialties.
-- Sao lưu: public.disease_triage_backup_20261010. Khôi phục: 20261010040000_reassign_disease_specialty_rollback.sql
begin;
with v(disease_key, code, name) as (values
  ('addison-suy-tuyen-thuong-than-nguyen-phat-4696', 'NOI_TIET', 'Nội tiết'),
  ('aids-4699', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('alkapton-nieu-4695', 'NOI_TIET', 'Nội tiết'),
  ('alzheimer-3112', 'THAN_KINH', 'Thần kinh'),
  ('am-anh-so-hai-4678', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('amip-an-nao-3153', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('ap-xe-3331', 'TONG_QUAT', 'Sức khỏe tổng quát'),
  ('ap-xe-gan-3238', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('ap-xe-gan-do-amip-4748', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('ap-xe-hau-mon-3332', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('ap-xe-nao-3205', 'THAN_KINH', 'Thần kinh'),
  ('ap-xe-nao-do-amip-4905', 'THAN_KINH', 'Thần kinh'),
  ('ap-xe-phoi-3333', 'HO_HAP', 'Nội hô hấp'),
  ('ap-xe-than-3334', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('ap-xe-vu-3283', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('au-dam-3335', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('au-trung-san-lon-4704', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('babesia-nhiem-trung-do-babesia-3337', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('bach-bien-3126', 'DA_LIEU', 'Da liễu'),
  ('bach-cau-cap-2976', 'UNG_BUOU', 'Ung bướu'),
  ('bach-hau-4743', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('bach-hau-thanh-quan-4726', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('bach-san-3346', 'DA_LIEU', 'Da liễu'),
  ('bach-tang-3154', 'DA_LIEU', 'Da liễu'),
  ('bai-liet-3109', 'THAN_KINH', 'Thần kinh'),
  ('bai-nao-3155', 'NHI_KHOA', 'Nhi khoa'),
  ('ban-chan-phang-4680', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('bang-quang-tang-hoat-3314', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('barrett-thuc-quan-3156', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('basedow-3241', 'NOI_TIET', 'Nội tiết'),
  ('benh-do-cryptosporidium-4741', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('benh-giac-mac-chop-3121', 'MAT', 'Mắt (Nhãn khoa)'),
  ('benh-gian-tinh-mach-chi-duoi-4865', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('benh-lang-ben-3152', 'DA_LIEU', 'Da liễu'),
  ('benh-lao-phoi-3183', 'HO_HAP', 'Nội hô hấp'),
  ('benh-lao-xuong-3137', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('benh-loan-duong-co-duchenne-3295', 'NHI_KHOA', 'Nhi khoa'),
  ('benh-ly-3160', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('benh-quai-bi-2972', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('benh-rubella-2973', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('benh-sa-sut-tri-tue-dementia-3294', 'THAN_KINH', 'Thần kinh'),
  ('benh-soi-2971', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('benh-still-o-nguoi-lon-3303', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('benh-ta-3149', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('benh-vay-nen-3093', 'DA_LIEU', 'Da liễu'),
  ('benh-xo-cung-bi-toan-the-4459', 'MIEN_DICH', 'Miễn dịch - Dị ứng'),
  ('beriberi-4701', 'TONG_QUAT', 'Sức khỏe tổng quát'),
  ('bo-dien-3157', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('bong-4782', 'CAP_CUU', 'Cấp cứu'),
  ('bong-de-3324', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('brucella-4739', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('buong-trung-da-nang-2932', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('buong-trung-da-nang-2996', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('buou-co-3182', 'NOI_TIET', 'Nội tiết'),
  ('cam-4711', 'THAN_KINH', 'Thần kinh'),
  ('can-thi-3119', 'MAT', 'Mắt (Nhãn khoa)'),
  ('cang-co-qua-muc-4891', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('cao-huyet-ap-o-tre-em-4717', 'NHI_KHOA', 'Nhi khoa'),
  ('cham-noi-3031', 'NHI_KHOA', 'Nhi khoa'),
  ('chan-an-than-kinh-bieng-an-tam-ly-3408', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('chan-thuong-day-chang-cheo-sau-3163', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('chan-thuong-day-chang-cheo-truoc-3164', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('chan-thuong-ham-mat-4694', 'RANG_HAM_MAT', 'Răng Hàm Mặt'),
  ('chan-thuong-lach-4700', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('chan-thuong-so-nao-3204', 'THAN_KINH', 'Thần kinh'),
  ('chan-thuong-sun-chem-4489', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('chan-voi-4110', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('chay-ran-chi-ran-3430', 'DA_LIEU', 'Da liễu'),
  ('chen-ep-day-than-kinh-then-2938', 'THAN_KINH', 'Thần kinh'),
  ('choc-dau-nam-da-dau-3433', 'DA_LIEU', 'Da liễu'),
  ('choc-mep-3125', 'DA_LIEU', 'Da liễu'),
  ('chong-mat-kich-phat-lanh-tinh-4902', 'THAN_KINH', 'Thần kinh'),
  ('chua-o-vet-mo-4705', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('co-that-thuc-quan-3087', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('co-tim-4883', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('co-tim-phi-dai-3305', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('coi-xuong-3026', 'NHI_KHOA', 'Nhi khoa'),
  ('con-ong-dong-mach-3024', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('crohn-3158', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('cum-3162', 'HO_HAP', 'Nội hô hấp'),
  ('cuong-kinh-3012', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('cuong-lach-3240', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('da-hong-cau-nguyen-phat-3248', 'HUYET_HOC', 'Huyết học'),
  ('da-oi-2986', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('da-u-tuy-xuong-3214', 'UNG_BUOU', 'Ung bướu'),
  ('dai-3150', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('dai-rat-2999', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('dai-rat-3083', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('dam-nieu-protein-nieu-3252', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('dau-co-vai-gay-3097', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('dau-dau-3037', 'THAN_KINH', 'Thần kinh'),
  ('dau-day-than-kinh-cham-3322', 'THAN_KINH', 'Thần kinh'),
  ('dau-day-than-kinh-sinh-ba-3519', 'THAN_KINH', 'Thần kinh'),
  ('dau-nua-dau-3028', 'THAN_KINH', 'Thần kinh'),
  ('dau-than-kinh-toa-4498', 'THAN_KINH', 'Thần kinh'),
  ('dau-that-nguc-that-tim-4677', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('day-thi-muon-3307', 'NOI_TIET', 'Nội tiết'),
  ('day-thi-som-o-nam-3261', 'NOI_TIET', 'Nội tiết'),
  ('day-thi-som-o-nu-3302', 'NOI_TIET', 'Nội tiết'),
  ('ddx-acute-dystonic-reactions', 'THAN_KINH', 'Thần kinh'),
  ('ddx-acute-laryngitis', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('ddx-acute-otitis-media', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('ddx-acute-pulmonary-edema', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('ddx-acute-rhinosinusitis', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('ddx-allergic-sinusitis', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('ddx-anaphylaxis', 'CAP_CUU', 'Cấp cứu'),
  ('ddx-anemia', 'HUYET_HOC', 'Huyết học'),
  ('ddx-atrial-fibrillation', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('ddx-boerhaave', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('ddx-bronchiectasis', 'HO_HAP', 'Nội hô hấp'),
  ('ddx-bronchiolitis', 'HO_HAP', 'Nội hô hấp'),
  ('ddx-bronchitis', 'HO_HAP', 'Nội hô hấp'),
  ('ddx-bronchospasm-asthma', 'HO_HAP', 'Nội hô hấp'),
  ('ddx-chagas', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('ddx-chronic-rhinosinusitis', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('ddx-cluster-headache', 'THAN_KINH', 'Thần kinh'),
  ('ddx-copd-exacerbation', 'HO_HAP', 'Nội hô hấp'),
  ('ddx-croup', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('ddx-ebola', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('ddx-epiglottitis', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('ddx-gerd', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('ddx-guillain-barre', 'THAN_KINH', 'Thần kinh'),
  ('ddx-hiv-initial', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('ddx-influenza', 'HO_HAP', 'Nội hô hấp'),
  ('ddx-inguinal-hernia', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('ddx-laryngospasm', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('ddx-localized-edema', 'TONG_QUAT', 'Sức khỏe tổng quát'),
  ('ddx-myasthenia-gravis', 'THAN_KINH', 'Thần kinh'),
  ('ddx-myocarditis', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('ddx-pancreatic-neoplasm', 'UNG_BUOU', 'Ung bướu'),
  ('ddx-panic-attack', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('ddx-pericarditis', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('ddx-pneumonia', 'HO_HAP', 'Nội hô hấp'),
  ('ddx-possible-nstemi-stemi', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('ddx-psvt', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('ddx-pulmonary-embolism', 'HO_HAP', 'Nội hô hấp'),
  ('ddx-pulmonary-neoplasm', 'UNG_BUOU', 'Ung bướu'),
  ('ddx-sarcoidosis', 'HO_HAP', 'Nội hô hấp'),
  ('ddx-scombroid-poisoning', 'CAP_CUU', 'Cấp cứu'),
  ('ddx-sle', 'MIEN_DICH', 'Miễn dịch - Dị ứng'),
  ('ddx-spontaneous-pneumothorax', 'HO_HAP', 'Nội hô hấp'),
  ('ddx-spontaneous-rib-fracture', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('ddx-stable-angina', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('ddx-tuberculosis', 'HO_HAP', 'Nội hô hấp'),
  ('ddx-unstable-angina', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('ddx-urti', 'HO_HAP', 'Nội hô hấp'),
  ('ddx-viral-pharyngitis', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('ddx-whooping-cough', 'HO_HAP', 'Nội hô hấp'),
  ('di-dang-mach-nao-3218', 'THAN_KINH', 'Thần kinh'),
  ('di-ung-sua-3131', 'MIEN_DICH', 'Miễn dịch - Dị ứng'),
  ('di-ung-thoi-tiet-3127', 'MIEN_DICH', 'Miễn dịch - Dị ứng'),
  ('di-ung-thuc-pham-3134', 'MIEN_DICH', 'Miễn dịch - Dị ứng'),
  ('dich-hach-3576', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('do-amip-4876', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('do-mo-hoi-trom-4722', 'DA_LIEU', 'Da liễu'),
  ('do-nocardia-4890', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('dong-kinh-4517', 'THAN_KINH', 'Thần kinh'),
  ('dot-quy-nao-2939', 'THAN_KINH', 'Thần kinh'),
  ('down-3074', 'NHI_KHOA', 'Nhi khoa'),
  ('duc-thuy-tinh-the-2944', 'MAT', 'Mắt (Nhãn khoa)'),
  ('gai-cot-song-3277', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('gai-den-3044', 'DA_LIEU', 'Da liễu'),
  ('gan-nhiem-mo-3147', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('gay-xuong-3602', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('gay-xuong-mac-4681', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('ghe-3129', 'DA_LIEU', 'Da liễu'),
  ('gian-mao-mach-xuat-huyet-di-truyen-4465', 'HUYET_HOC', 'Huyết học'),
  ('gian-nao-that-4501', 'THAN_KINH', 'Thần kinh'),
  ('gian-ong-dan-sua-3141', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('gian-phe-quan-2966', 'HO_HAP', 'Nội hô hấp'),
  ('gian-tinh-mach-chan-2941', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('gian-tinh-mach-thuc-quan-4864', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('gian-tinh-mach-thung-tinh-2968', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('gioi-leo-3132', 'DA_LIEU', 'Da liễu'),
  ('giun-chi-3144', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('giun-kim-3192', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('giun-moc-3193', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('giun-toc-3138', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('gout-gut-3052', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('gu-cot-song-4686', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('ha-cam-4685', 'DA_LIEU', 'Da liễu'),
  ('ha-canxi-mau-3185', 'NOI_TIET', 'Nội tiết'),
  ('ha-duong-huyet-4863', 'NOI_TIET', 'Nội tiết'),
  ('ha-huyet-ap-tu-the-dung-3639', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('ha-kali-mau-4880', 'NOI_TIET', 'Nội tiết'),
  ('ha-than-nhiet-o-tre-so-sinh-3250', 'NHI_KHOA', 'Nhi khoa'),
  ('hach-nen-3642', 'THAN_KINH', 'Thần kinh'),
  ('hay-quen-3646', 'THAN_KINH', 'Thần kinh'),
  ('hen-phe-quan-2949', 'HO_HAP', 'Nội hô hấp'),
  ('hen-suyen-4684', 'HO_HAP', 'Nội hô hấp'),
  ('hep-bao-quy-dau-2928', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('hep-dong-mach-canh-3648', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('hep-dong-mach-phoi-4878', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('hep-dong-mach-than-3650', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('hep-duong-mat-bam-sinh-3651', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('hep-eo-dong-mach-chu-4805', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('hep-hau-mon-o-tre-em-3236', 'NHI_KHOA', 'Nhi khoa'),
  ('hep-nieu-dao-3139', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('hep-nieu-quan-4503', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('hep-ong-song-4473', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('hep-thanh-quan-3654', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('hep-thuc-quan-3326', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('hep-van-dong-mach-chu-3213', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('hep-van-hai-la-3135', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('hiv-2975', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('ho-eo-tu-cung-2980', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('ho-ga-3143', 'HO_HAP', 'Nội hô hấp'),
  ('ho-ham-ech-3309', 'RANG_HAM_MAT', 'Răng Hàm Mặt'),
  ('ho-van-dong-mach-chu-3029', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('hoai-tu-chom-xuong-dui-3221', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('hoai-tu-vo-mach-3660', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('hoang-so-khi-ngu-hoang-so-ban-dem-4915', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('hodgkin-3159', 'UNG_BUOU', 'Ung bướu'),
  ('hoi-chung-albright-3667', 'NOI_TIET', 'Nội tiết'),
  ('hoi-chung-alport-3669', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('hoi-chung-antiphospholipid-3202', 'HUYET_HOC', 'Huyết học'),
  ('hoi-chung-apallic-4713', 'THAN_KINH', 'Thần kinh'),
  ('hoi-chung-asperger-3670', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('hoi-chung-bartter-3674', 'NOI_TIET', 'Nội tiết'),
  ('hoi-chung-beckwith-wiedemann-3675', 'NHI_KHOA', 'Nhi khoa'),
  ('hoi-chung-behcet-3676', 'MIEN_DICH', 'Miễn dịch - Dị ứng'),
  ('hoi-chung-budd-chiari-3680', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('hoi-chung-carcinoid-4740', 'UNG_BUOU', 'Ung bướu'),
  ('hoi-chung-catatonia-4791', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('hoi-chung-chan-khong-nghi-4734', 'THAN_KINH', 'Thần kinh'),
  ('hoi-chung-crouzon-4792', 'NHI_KHOA', 'Nhi khoa'),
  ('hoi-chung-cushing-4793', 'NOI_TIET', 'Nội tiết'),
  ('hoi-chung-dap-ung-viem-he-thong-4794', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('hoi-chung-dau-co-4901', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('hoi-chung-dau-nhuc-vung-so-mat-3312', 'THAN_KINH', 'Thần kinh'),
  ('hoi-chung-dau-that-lung-dau-lung-vung-thap-3168', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('hoi-chung-dressler-4867', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('hoi-chung-dumping-4908', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('hoi-chung-duoi-ngua-4909', 'THAN_KINH', 'Thần kinh'),
  ('hoi-chung-ehlers-danlos-4910', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('hoi-chung-eisenmenger-4454', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('hoi-chung-evans-3708', 'HUYET_HOC', 'Huyết học'),
  ('hoi-chung-fanconi-3709', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('hoi-chung-felty-3710', 'MIEN_DICH', 'Miễn dịch - Dị ứng'),
  ('hoi-chung-fragile-x-3712', 'NHI_KHOA', 'Nhi khoa'),
  ('hoi-chung-gan-than-3718', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('hoi-chung-ganser-3719', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('hoi-chung-gilbert-3722', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('hoi-chung-goodpasture-3723', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('hoi-chung-hellp-3725', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('hoi-chung-hong-vu-cong-4879', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('hoi-chung-horner-3727', 'THAN_KINH', 'Thần kinh'),
  ('hoi-chung-khang-the-khang-phospholipid-3732', 'HUYET_HOC', 'Huyết học'),
  ('hoi-chung-klinefelter-3737', 'NOI_TIET', 'Nội tiết'),
  ('hoi-chung-lyell-3742', 'DA_LIEU', 'Da liễu'),
  ('hoi-chung-mallory-weiss-3743', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('hoi-chung-marfan-3744', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('hoi-chung-met-moi-4881', 'TONG_QUAT', 'Sức khỏe tổng quát'),
  ('hoi-chung-mittelschmerz-4913', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('hoi-chung-mong-va-xuong-banh-che-3753', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('hoi-chung-nghien-giat-toc-3756', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('hoi-chung-ngu-ru-4904', 'THAN_KINH', 'Thần kinh'),
  ('hoi-chung-noonan-3761', 'NHI_KHOA', 'Nhi khoa'),
  ('hoi-chung-ong-co-chan-3763', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('hoi-chung-patau-3036', 'NHI_KHOA', 'Nhi khoa'),
  ('hoi-chung-peutz-jeghers-3768', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('hoi-chung-prader-willi-3770', 'NOI_TIET', 'Nội tiết'),
  ('hoi-chung-qt-keo-dai-3771', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('hoi-chung-quai-mu-3773', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('hoi-chung-raynaud-3775', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('hoi-chung-rett-4789', 'THAN_KINH', 'Thần kinh'),
  ('hoi-chung-reye-4718', 'THAN_KINH', 'Thần kinh'),
  ('hoi-chung-ruot-kich-thich-3004', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('hoi-chung-ruot-kich-thich-3045', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('hoi-chung-sau-bai-liet-4806', 'THAN_KINH', 'Thần kinh'),
  ('hoi-chung-seckel-nguoi-ti-hon-4808', 'NHI_KHOA', 'Nhi khoa'),
  ('hoi-chung-sheehan-4809', 'NOI_TIET', 'Nội tiết'),
  ('hoi-chung-sieu-nu-hoi-chung-3x-4612', 'TONG_QUAT', 'Sức khỏe tổng quát'),
  ('hoi-chung-sjogren-4810', 'MIEN_DICH', 'Miễn dịch - Dị ứng'),
  ('hoi-chung-smith-lemli-opitz-4862', 'NHI_KHOA', 'Nhi khoa'),
  ('hoi-chung-soc-nhiem-doc-4733', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('hoi-chung-stevens-johnson-4796', 'DA_LIEU', 'Da liễu'),
  ('hoi-chung-sudeck-loan-duong-giao-cam-phan-xa-4797', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('hoi-chung-than-hu-o-nguoi-lon-3208', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('hoi-chung-thien-than-3801', 'NHI_KHOA', 'Nhi khoa'),
  ('hoi-chung-tien-kinh-nguyet-4749', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('hoi-chung-tiet-hormon-khang-bai-nieu-adh-khong-phu-hop-4732', 'NOI_TIET', 'Nội tiết'),
  ('hoi-chung-tourette-3807', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('hoi-chung-truyen-mau-song-thai-4897', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('hoi-chung-ure-huyet-tan-huyet-4786', 'HUYET_HOC', 'Huyết học'),
  ('hoi-chung-volkmann-4868', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('hoi-chung-west-4869', 'THAN_KINH', 'Thần kinh'),
  ('hoi-chung-wiskott-aldrich-4870', 'HUYET_HOC', 'Huyết học'),
  ('hoi-chung-xyy-4899', 'TONG_QUAT', 'Sức khỏe tổng quát'),
  ('hoi-chung-zollinger-ellison-4871', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('hoi-mieng-4872', 'RANG_HAM_MAT', 'Răng Hàm Mặt'),
  ('hoi-nach-4441', 'DA_LIEU', 'Da liễu'),
  ('hon-me-4716', 'CAP_CUU', 'Cấp cứu'),
  ('hong-ban-da-dang-4873', 'DA_LIEU', 'Da liễu'),
  ('hong-ban-nut-3824', 'DA_LIEU', 'Da liễu'),
  ('hong-cau-luoi-liem-3825', 'HUYET_HOC', 'Huyết học'),
  ('huyet-khoi-cuc-mau-dong-4874', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('huyet-khoi-tinh-mach-sau-2964', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('jet-lag-3184', 'TONG_QUAT', 'Sức khỏe tổng quát'),
  ('kawasaki-viem-mach-mau-2977', 'NHI_KHOA', 'Nhi khoa'),
  ('khi-phe-thung-3088', 'HO_HAP', 'Nội hô hấp'),
  ('kho-mat-3081', 'MAT', 'Mắt (Nhãn khoa)'),
  ('khoeo-chan-bam-sinh-3103', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('khong-dung-nap-lactose-3845', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('lac-mat-3104', 'MAT', 'Mắt (Nhãn khoa)'),
  ('lac-noi-mac-tu-cung-2963', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('lao-co-xuong-4892', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('lao-cot-song-3140', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('lao-da-va-mo-duoi-da-4687', 'DA_LIEU', 'Da liễu'),
  ('lao-hach-3124', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('lao-he-than-kinh-4895', 'THAN_KINH', 'Thần kinh'),
  ('lao-he-tiet-nieu-sinh-duc-4804', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('lao-ke-4877', 'HO_HAP', 'Nội hô hấp'),
  ('lao-mang-bung-4721', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('lao-mang-phoi-4728', 'HO_HAP', 'Nội hô hấp'),
  ('lao-o-mat-4729', 'MAT', 'Mắt (Nhãn khoa)'),
  ('lao-phoi-2950', 'HO_HAP', 'Nội hô hấp'),
  ('lao-ruot-3133', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('lao-ruot-phuc-mac-va-mac-treo-cac-tuyen-lao-bung-3868', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('lao-thanh-quan-4500', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('lao-vu-4456', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('lau-3009', 'DA_LIEU', 'Da liễu'),
  ('lech-khop-can-3023', 'RANG_HAM_MAT', 'Răng Hàm Mặt'),
  ('legionnaire-4919', 'HO_HAP', 'Nội hô hấp'),
  ('leukemia-cap-3297', 'UNG_BUOU', 'Ung bướu'),
  ('leukemia-kinh-dong-bach-cau-hat-cml-4783', 'UNG_BUOU', 'Ung bướu'),
  ('lichen-nitidus-3874', 'DA_LIEU', 'Da liễu'),
  ('lichen-xo-hoa-4875', 'DA_LIEU', 'Da liễu'),
  ('liet-co-mo-thanh-quan-4471', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('liet-day-than-kinh-so-6-3877', 'THAN_KINH', 'Thần kinh'),
  ('liet-duong-3316', 'NAM_KHOA', 'Nam khoa'),
  ('liet-mat-3254', 'THAN_KINH', 'Thần kinh'),
  ('liet-nua-nguoi-3878', 'THAN_KINH', 'Thần kinh'),
  ('liet-ruot-3879', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('liet-tu-chi-3881', 'THAN_KINH', 'Thần kinh'),
  ('lo-tieu-dong-thap-3186', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('loan-duong-mo-4893', 'NOI_TIET', 'Nội tiết'),
  ('loan-san-co-tu-cung-4884', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('loan-san-sun-xuong-4600', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('loan-thi-3118', 'MAT', 'Mắt (Nhãn khoa)'),
  ('loang-xuong-3027', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('loc-tach-dong-mach-chu-2993', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('loet-da-day-ta-trang-4535', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('loet-giac-mac-3896', 'MAT', 'Mắt (Nhãn khoa)'),
  ('loet-hanh-ta-trang-3293', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('loet-thuc-quan-3899', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('long-ruot-3016', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('lun-3907', 'NOI_TIET', 'Nội tiết'),
  ('luoi-ban-do-3908', 'RANG_HAM_MAT', 'Răng Hàm Mặt'),
  ('lupus-ban-do-3276', 'MIEN_DICH', 'Miễn dịch - Dị ứng'),
  ('ly-amip-cap-4693', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('ly-amip-duong-ruot-man-tinh-4703', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('ly-do-balantidium-4737', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('ly-truc-trung-ly-truc-khuan-3910', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('lyme-3911', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('mach-vanh-3269', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('man-duc-nam-3094', 'NAM_KHOA', 'Nam khoa'),
  ('man-kinh-som-3188', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('mat-khuu-giac-3919', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('mat-ngu-3923', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('mat-ngu-man-tinh-3101', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('mat-thinh-luc-diec-tai-3189', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('mat-tri-nho-3177', 'THAN_KINH', 'Thần kinh'),
  ('mau-kho-dong-3219', 'HUYET_HOC', 'Huyết học'),
  ('meniere-roi-loan-thinh-luc-3267', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('mon-rang-3179', 'RANG_HAM_MAT', 'Răng Hàm Mặt'),
  ('mong-quap-mong-moc-nguoc-3946', 'DA_LIEU', 'Da liễu'),
  ('mong-thit-3947', 'MAT', 'Mắt (Nhãn khoa)'),
  ('moyamonya-4911', 'THAN_KINH', 'Thần kinh'),
  ('mu-mat-4715', 'MAT', 'Mắt (Nhãn khoa)'),
  ('mu-mau-3190', 'MAT', 'Mắt (Nhãn khoa)'),
  ('muc-coc-3210', 'DA_LIEU', 'Da liễu'),
  ('mun-rop-herpes-sinh-duc-3228', 'DA_LIEU', 'Da liễu'),
  ('mun-rop-lanh-tinh-3206', 'DA_LIEU', 'Da liễu'),
  ('nam-da-3191', 'DA_LIEU', 'Da liễu'),
  ('nam-da-dui-3964', 'DA_LIEU', 'Da liễu'),
  ('nam-da-hac-lao-3963', 'DA_LIEU', 'Da liễu'),
  ('nam-mong-3968', 'DA_LIEU', 'Da liễu'),
  ('nam-thanh-quan-4708', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('nang-nuoc-thung-tinh-o-tre-em-3249', 'NHI_KHOA', 'Nhi khoa'),
  ('nang-than-4914', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('nang-tuy-3978', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('nang-tuyen-bartholin-viem-tuyen-bartholin-3979', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('nao-gan-hon-me-gan-3981', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('nao-ung-thuy-3172', 'THAN_KINH', 'Thần kinh'),
  ('nao-wernicke-do-ruou-4692', 'THAN_KINH', 'Thần kinh'),
  ('nghien-game-4720', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('nghien-ma-tuy-4719', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('ngo-doc-thuc-pham-3244', 'CAP_CUU', 'Cấp cứu'),
  ('ngoai-tam-thu-ngoai-tam-thu-that-3992', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('ngon-chan-hinh-bua-4886', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('ngu-ngay-3212', 'HO_HAP', 'Nội hô hấp'),
  ('ngung-tho-khi-ngu-4887', 'HO_HAP', 'Nội hô hấp'),
  ('nha-chu-3161', 'RANG_HAM_MAT', 'Răng Hàm Mặt'),
  ('nhau-bong-non-3098', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('nhau-cai-rang-luoc-3059', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('nhau-tien-dao-3062', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('nhiem-doc-thai-nghen-3099', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('nhiem-echinococcus-4888', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('nhiem-giardia-nhiem-trung-ruot-non-do-giardia-4889', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('nhiem-khuan-hau-san-3282', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('nhiem-khuan-huyet-nao-mo-cau-2943', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('nhiem-lau-cau-4885', 'DA_LIEU', 'Da liễu'),
  ('nhiem-leptospira-4898', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('nhiem-nam-candida-nhiem-trung-nam-men-4016', 'DA_LIEU', 'Da liễu'),
  ('nhiem-nam-cryptococcus-4017', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('nhiem-nam-histoplasma-vi-nam-histoplasma-4018', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('nhiem-trung-do-tu-cau-vang-4730', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('nhiem-trung-huyet-do-lien-cau-4736', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('nhiem-trung-oi-2984', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('nhiem-vi-khuan-hp-3068', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('nhiem-xoan-khuan-vang-da-leptospira-4738', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('nhiet-mieng-loet-mieng-3106', 'RANG_HAM_MAT', 'Răng Hàm Mặt'),
  ('nhip-tim-cham-4679', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('nhoi-mau-co-tim-cap-4866', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('nhoi-mau-nao-4742', 'THAN_KINH', 'Thần kinh'),
  ('nhuoc-co-4676', 'THAN_KINH', 'Thần kinh'),
  ('nhuoc-thi-3123', 'MAT', 'Mắt (Nhãn khoa)'),
  ('nieu-quan-gian-4689', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('noi-lap-3034', 'THAN_KINH', 'Thần kinh'),
  ('nut-ke-hau-mon-3235', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('parkinson-3113', 'THAN_KINH', 'Thần kinh'),
  ('phi-dai-am-vat-3246', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('phi-dai-cuon-mui-3111', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('phi-dai-tien-liet-tuyen-2930', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('phinh-dong-mach-chu-2992', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('phinh-dong-mach-nao-3145', 'THAN_KINH', 'Thần kinh'),
  ('phong-4735', 'DA_LIEU', 'Da liễu'),
  ('polyp-co-tu-cung-3225', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('polyp-mui-3151', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('polyp-ong-tieu-hoa-3063', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('polyp-thanh-quan-3117', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('polyp-tui-mat-3237', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('protein-nieu-thai-ky-3181', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('quang-ga-3080', 'MAT', 'Mắt (Nhãn khoa)'),
  ('rach-bong-vong-mac-3200', 'MAT', 'Mắt (Nhãn khoa)'),
  ('rach-giac-mac-3033', 'MAT', 'Mắt (Nhãn khoa)'),
  ('ram-long-3187', 'DA_LIEU', 'Da liễu'),
  ('ri-oi-2985', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('ro-mao-mach-4450', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('roi-loan-cuong-duong-2926', 'NAM_KHOA', 'Nam khoa'),
  ('roi-loan-gan-o-tre-em-4697', 'NHI_KHOA', 'Nhi khoa'),
  ('roi-loan-hoang-so-4144', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('roi-loan-lipid-mau-3120', 'NOI_TIET', 'Nội tiết'),
  ('roi-loan-luong-cuc-4759', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('roi-loan-nhip-tim-3136', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('roi-loan-noi-tiet-to-2942', 'NOI_TIET', 'Nội tiết'),
  ('roi-loan-sinh-tuy-mds-4784', 'HUYET_HOC', 'Huyết học'),
  ('roi-loan-tang-dong-giam-chu-y-adhd-4157', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('roi-loan-than-kinh-thuc-vat-4770', 'THAN_KINH', 'Thần kinh'),
  ('roi-loan-tien-dinh-3032', 'THAN_KINH', 'Thần kinh'),
  ('roi-loan-tieu-hoa-o-tre-3018', 'NHI_KHOA', 'Nhi khoa'),
  ('roi-loan-xuat-tinh-2957', 'NAM_KHOA', 'Nam khoa'),
  ('rom-say-4170', 'DA_LIEU', 'Da liễu'),
  ('rong-kinh-3008', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('sa-sinh-duc-3298', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('sa-truc-trang-3266', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('san-la-gan-3291', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('sau-rang-4504', 'RANG_HAM_MAT', 'Răng Hàm Mặt'),
  ('sinh-non-3220', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('soi-bang-quang-3274', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('soi-mat-3230', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('soi-nieu-quan-3273', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('soi-than-3096', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('son-tieu-2997', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('song-thi-3321', 'MAT', 'Mắt (Nhãn khoa)'),
  ('sot-phat-ban-2970', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('sot-ret-4443', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('sot-sieu-vi-2974', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('sot-ve-mo-3319', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('sui-mao-ga-2995', 'DA_LIEU', 'Da liễu'),
  ('suy-buong-trung-2959', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('suy-dinh-duong-3071', 'TONG_QUAT', 'Sức khỏe tổng quát'),
  ('suy-dinh-duong-the-thap-coi-3281', 'NHI_KHOA', 'Nhi khoa'),
  ('suy-giap-3245', 'NOI_TIET', 'Nội tiết'),
  ('suy-giap-bam-sinh-3270', 'NOI_TIET', 'Nội tiết'),
  ('suy-thai-2989', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('suy-thai-trong-tu-cung-3279', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('suy-than-3075', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('suy-than-cap-3198', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('suy-than-cap-3275', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('suy-than-man-3199', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('suy-tim-3262', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('suy-tim-cap-3070', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('suy-tim-trai-3795', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('suy-tinh-mach-chan-3025', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('suy-tuyen-thuong-than-3053', 'NOI_TIET', 'Nội tiết'),
  ('suy-tuyen-yen-3046', 'NOI_TIET', 'Nội tiết'),
  ('tac-mach-oi-2988', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('tac-ong-dan-tinh-2937', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('tac-ong-dan-trung-2933', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('tac-ong-phong-tinh-3067', 'NAM_KHOA', 'Nam khoa'),
  ('tac-ruot-so-sinh-3015', 'NHI_KHOA', 'Nhi khoa'),
  ('tac-tia-sua-3226', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('tac-tuyen-le-3110', 'MAT', 'Mắt (Nhãn khoa)'),
  ('tac-tuyen-le-o-tre-em-2947', 'NHI_KHOA', 'Nhi khoa'),
  ('tac-voi-trung-2934', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('tang-acid-uric-mau-3115', 'NOI_TIET', 'Nội tiết'),
  ('tang-huyet-ap-3089', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('tang-huyet-ap-nguyen-phat-4744', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('tang-huyet-ap-thai-ky-3114', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('tang-huyet-ap-thu-phat-4682', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('tang-thong-khi-4731', 'HO_HAP', 'Nội hô hấp'),
  ('tang-tiet-mo-hoi-3284', 'DA_LIEU', 'Da liễu'),
  ('tao-bon-3001', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('te-bao-than-kinh-van-dong-4714', 'THAN_KINH', 'Thần kinh'),
  ('te-bi-tay-chan-3272', 'THAN_KINH', 'Thần kinh'),
  ('teo-day-than-kinh-thi-giac-3078', 'MAT', 'Mắt (Nhãn khoa)'),
  ('teo-thuc-quan-4445', 'NHI_KHOA', 'Nhi khoa'),
  ('thai-cham-phat-trien-trong-tu-cung-3280', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('thai-chet-luu-4447', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('thai-ngoai-tu-cung-2981', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('thai-trung-chua-trung-2979', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('thalassemia-tan-mau-bam-sinh-2978', 'HUYET_HOC', 'Huyết học'),
  ('than-4745', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('than-da-nang-3286', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('than-u-nuoc-4244', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('thap-tim-4894', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('thap-tim-o-tre-em-3292', 'NHI_KHOA', 'Nhi khoa'),
  ('thien-dau-thong-tang-nhan-ap-2946', 'MAT', 'Mắt (Nhãn khoa)'),
  ('thieu-mau-3007', 'HUYET_HOC', 'Huyết học'),
  ('thieu-mau-co-tim-3178', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('thieu-mau-do-thieu-sat-2991', 'HUYET_HOC', 'Huyết học'),
  ('thieu-mau-do-thieu-vitamin-b12-4702', 'HUYET_HOC', 'Huyết học'),
  ('thieu-mau-tan-huyet-2990', 'HUYET_HOC', 'Huyết học'),
  ('thieu-men-g6pd-3173', 'HUYET_HOC', 'Huyết học'),
  ('thieu-nang-tuan-hoan-nao-3259', 'THAN_KINH', 'Thần kinh'),
  ('thieu-oi-2987', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('thieu-san-men-rang-4597', 'RANG_HAM_MAT', 'Răng Hàm Mặt'),
  ('thoai-hoa-cot-song-co-4499', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('thoai-hoa-cot-song-that-lung-3169', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('thoai-hoa-khop-goi-3066', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('thoai-hoa-khop-hang-3229', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('thoai-hoa-vong-mac-3072', 'MAT', 'Mắt (Nhãn khoa)'),
  ('thoat-vi-ben-nguoi-lon-3253', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('thoat-vi-ben-tre-em-3255', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('thoat-vi-dia-dem-3090', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('thoat-vi-dui-3239', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('thoat-vi-hoanh-o-tre-em-4706', 'NHI_KHOA', 'Nhi khoa'),
  ('thoat-vi-nao-4709', 'THAN_KINH', 'Thần kinh'),
  ('thoat-vi-ron-4661', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('thong-kinh-2994', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('thong-lien-nhi-3060', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('thong-lien-that-3107', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('thua-sat-4466', 'HUYET_HOC', 'Huyết học'),
  ('thuong-han-3289', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('thuy-dau-2969', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('thuyen-tac-oi-3176', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('thuyen-tac-phoi-4442', 'HO_HAP', 'Nội hô hấp'),
  ('tien-man-kinh-3095', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('tien-san-giat-3233', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('tieu-chay-3002', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('tieu-chay-cap-3006', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('tieu-chay-nhiem-trung-4753', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('tieu-chay-rota-3014', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('tieu-duong-thai-ky-3091', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('tieu-duong-tuyp-1-3041', 'NOI_TIET', 'Nội tiết'),
  ('tieu-duong-tuyp-2-3042', 'NOI_TIET', 'Nội tiết'),
  ('tim-bam-sinh-3108', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('tim-bam-sinh-ebstein-4707', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('tinh-hoan-an-4588', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('tinh-trung-yeu-3076', 'NAM_KHOA', 'Nam khoa'),
  ('tram-cam-2982', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('tram-cam-sau-sinh-2983', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('tran-dich-mang-phoi-2948', 'HO_HAP', 'Nội hô hấp'),
  ('tran-khi-mang-phoi-tu-phat-2965', 'HO_HAP', 'Nội hô hấp'),
  ('trao-nguoc-da-day-thuc-quan-3003', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('trao-nguoc-da-day-thuc-quan-o-tre-em-3017', 'NHI_KHOA', 'Nhi khoa'),
  ('tri-3000', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('tri-ngoai-3257', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('tri-noi-3064', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('tu-chung-fallot-3203', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('tu-ky-o-nguoi-lon-3247', 'TAM_THAN', 'Trung tâm chăm sóc sức khỏe tinh thần tích hợp'),
  ('tu-ky-o-tre-em-3232', 'NHI_KHOA', 'Nhi khoa'),
  ('tui-thua-thuc-quan-4446', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('u-lach-lanh-tinh-4785', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('u-lanh-thuc-quan-3325', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('u-lympho-khong-hodgkin-4912', 'UNG_BUOU', 'Ung bướu'),
  ('u-lympho-te-bao-t-4509', 'UNG_BUOU', 'Ung bướu'),
  ('u-mach-mau-gan-4277', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('u-mang-nao-4510', 'THAN_KINH', 'Thần kinh'),
  ('u-mau-4683', 'DA_LIEU', 'Da liễu'),
  ('u-nang-buong-trung-2931', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('u-nang-ong-mat-chu-3264', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('u-nao-o-tre-em-3174', 'NHI_KHOA', 'Nhi khoa'),
  ('u-nguyen-bao-than-kinh-3320', 'UNG_BUOU', 'Ung bướu'),
  ('u-nguyen-bao-vong-mac-3318', 'UNG_BUOU', 'Ung bướu'),
  ('u-nhay-ruot-thua-3020', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('u-sun-mang-hoat-dich-4472', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('u-tai-3310', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('u-te-bao-khong-lo-4453', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('u-thuc-quan-polyp-thuc-quan-lanh-tinh-3021', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('u-tim-4688', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('u-tuyen-nuoc-bot-3311', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('u-tuyen-thuong-than-3054', 'NOI_TIET', 'Nội tiết'),
  ('u-tuyen-yen-3050', 'NOI_TIET', 'Nội tiết'),
  ('u-xo-tu-cung-2935', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('u-xo-vom-mui-hong-4474', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('u-xuong-ac-tinh-4906', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-am-dao-4907', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-am-ho-3296', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-amidan-4313', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-bang-quang-3242', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-bieu-mo-mui-hong-4314', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-bieu-mo-te-bao-day-4315', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-bieu-mo-te-bao-vay-4316', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-bieu-mo-tieu-thuy-tai-cho-4317', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-bieu-mo-tieu-thuy-xam-lan-4916', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-buong-trung-2960', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-co-tu-cung-3035', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-da-4452', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-da-dau-4451', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-da-day-3092', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-dai-trang-3065', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-duong-vat-3146', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-gan-3043', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-gan-nguyen-phat-3201', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-ha-hong-3207', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-hac-to-da-4723', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-hau-mon-3317', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-khoang-mieng-3263', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-la-lach-4725', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-luoi-3038', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-nao-3260', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-noi-mac-tu-cung-2936', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-phe-quan-phoi-nguyen-phat-3287', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-phoi-3039', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-ruot-non-3315', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-than-3069', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-thanh-quan-3105', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-thuc-quan-3022', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-tien-liet-tuyen-2929', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-tinh-hoan-3100', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-tu-cung-4788', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-tui-mat-4724', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-tuy-3216', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-tuyen-giap-3195', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-tuyen-nuoc-bot-3288', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-tuyen-tuy-3055', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-vom-hong-3170', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-vu-2924', 'UNG_BUOU', 'Ung bướu'),
  ('ung-thu-xuong-3142', 'UNG_BUOU', 'Ung bướu'),
  ('uon-van-3130', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('van-hai-la-3171', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('vang-da-benh-ly-3234', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('vang-da-so-sinh-3209', 'NHI_KHOA', 'Nhi khoa'),
  ('veo-cot-song-4469', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-am-dao-4342', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('viem-amidan-2956', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('viem-bang-quang-3057', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('viem-bang-quang-cap-3167', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('viem-buong-trung-2961', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('viem-can-gan-chan-3265', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-cau-than-3196', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('viem-chop-xoay-3258', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-co-ap-xe-co-3300', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-co-tim-3308', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('viem-cot-song-dinh-khop-3299', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-da-co-3301', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-da-co-dia-3086', 'DA_LIEU', 'Da liễu'),
  ('viem-da-re-day-than-kinh-4457', 'THAN_KINH', 'Thần kinh'),
  ('viem-dai-be-than-3197', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('viem-dai-trang-3061', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('viem-day-than-kinh-thi-giac-3040', 'MAT', 'Mắt (Nhãn khoa)'),
  ('viem-duong-ho-hap-duoi-2954', 'HO_HAP', 'Nội hô hấp'),
  ('viem-duong-ho-hap-tren-2967', 'HO_HAP', 'Nội hô hấp'),
  ('viem-duong-tiet-nieu-2998', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('viem-gan-a-3128', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('viem-gan-b-3116', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('viem-gan-chop-xoay-4861', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-gan-nhi-dau-vai-3256', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-hau-mon-4698', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('viem-hong-cap-2952', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('viem-hong-man-tinh-4460', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('viem-khop-3227', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-khop-dang-thap-3285', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-khop-phan-ung-4458', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-loet-da-day-3122', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('viem-loi-cau-ngoai-xuong-canh-tay-4455', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-mang-hoat-dich-3304', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-mang-nao-do-nao-mo-cau-3148', 'THAN_KINH', 'Thần kinh'),
  ('viem-mang-nao-mu-3084', 'THAN_KINH', 'Thần kinh'),
  ('viem-mang-ngoai-tim-4710', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('viem-mang-ngoai-tim-co-that-4675', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('viem-mang-oi-3251', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('viem-mao-mach-di-ung-4554', 'MIEN_DICH', 'Miễn dịch - Dị ứng'),
  ('viem-mao-tinh-hoan-3048', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('viem-mu-mang-phoi-3306', 'HO_HAP', 'Nội hô hấp'),
  ('viem-mui-di-ung-4751', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('viem-mui-hong-3290', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('viem-nang-long-4691', 'DA_LIEU', 'Da liễu'),
  ('viem-nao-nhat-ban-3082', 'THAN_KINH', 'Thần kinh'),
  ('viem-nhiem-mieng-4630', 'RANG_HAM_MAT', 'Răng Hàm Mặt'),
  ('viem-niem-mac-hang-vi-da-day-3058', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('viem-nieu-dao-4502', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('viem-nuou-3278', 'RANG_HAM_MAT', 'Răng Hàm Mặt'),
  ('viem-ong-dan-trung-2962', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('viem-phe-quan-2955', 'HO_HAP', 'Nội hô hấp'),
  ('viem-phoi-o-tre-em-2951', 'NHI_KHOA', 'Nhi khoa'),
  ('viem-quanh-khop-vai-3271', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-ruot-do-virus-4790', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('viem-ruot-thua-3019', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('viem-tac-ong-dan-tinh-4467', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('viem-tai-giua-cap-tinh-3268', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('viem-tai-giua-man-tinh-o-tre-em-3180', 'NHI_KHOA', 'Nhi khoa'),
  ('viem-thanh-quan-3165', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('viem-thanh-quan-cap-tinh-3102', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('viem-thanh-quan-man-tinh-3085', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('viem-tieu-phe-quan-3217', 'HO_HAP', 'Nội hô hấp'),
  ('viem-tinh-hoan-2958', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('viem-tinh-mach-2940', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('viem-tui-mat-4468', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('viem-tui-tinh-2925', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('viem-tuy-cap-3005', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('viem-tuy-cap-o-tre-em-3013', 'NHI_KHOA', 'Nhi khoa'),
  ('viem-tuy-xuong-3194', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-tuyen-nuoc-bot-3056', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('viem-tuyen-tien-liet-2927', 'THAN_TIET_NIEU', 'Thận - Tiết niệu'),
  ('viem-tuyen-vu-3175', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('viem-va-3166', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('viem-xoang-2953', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('viem-xuong-3215', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('viem-xuong-tai-chum-3313', 'TAI_MUI_HONG', 'Tai - Mũi - Họng'),
  ('vien-thi-3049', 'MAT', 'Mắt (Nhãn khoa)'),
  ('virus-ebola-4917', 'TRUYEN_NHIEM', 'Truyền nhiễm'),
  ('vo-kinh-3011', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('vo-oi-non-3222', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('vo-sinh-nam-3224', 'NAM_KHOA', 'Nam khoa'),
  ('vo-sinh-nu-3223', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('vo-tu-cung-4470', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('voi-hoa-cot-song-3073', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('vong-mac-2945', 'MAT', 'Mắt (Nhãn khoa)'),
  ('xep-dot-song-3243', 'XUONG_KHOP', 'Chấn thương chỉnh hình - Y học thể thao'),
  ('xo-gan-mat-bu-3323', 'TIEU_HOA', 'Tiêu hóa - Gan mật'),
  ('xo-vua-dong-mach-3030', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('xo-vua-dong-mach-nao-4896', 'THAN_KINH', 'Thần kinh'),
  ('xo-vua-dong-mach-ngoai-bien-4882', 'TIM_MACH', 'Trung tâm Tim mạch'),
  ('xoan-buong-trung-3077', 'SAN_PHU_KHOA', 'Sản phụ khoa'),
  ('xuat-huyet-giam-tieu-cau-4690', 'HUYET_HOC', 'Huyết học'),
  ('xuat-huyet-vong-mac-3079', 'MAT', 'Mắt (Nhãn khoa)'),
  ('xuat-tinh-nguoc-3047', 'NAM_KHOA', 'Nam khoa')
)
update public.disease_triage d set
  primary_specialty_code = v.code,
  primary_specialty_name = v.name,
  updated_at = now()
from v
where d.disease_key = v.disease_key
  and (d.primary_specialty_code is distinct from v.code or d.primary_specialty_name is distinct from v.name);
commit;
