import { PatientQueueItem, HITLMetrics } from './types';

export const INITIAL_METRICS: HITLMetrics = {
  totalQueue: 25,
  needTakeoverCount: 4,
  inInterventionCount: 2,
  aiHandlingCount: 19,
  slaTargetSeconds: 90,
  slaCurrentSeconds: 24,
  shiftAccuracyPercent: 99.2,
  completedCasesCount: 18,
  zeroDefectCount: 0,
};

export const MOCK_PATIENTS: PatientQueueItem[] = [
  {
    id: 'p-8831',
    code: 'BN-2024-8831',
    name: 'Vũ Thành Long',
    age: 46,
    gender: 'Nam',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    riskLevel: 'CAO',
    status: 'need_takeover',
    timeAgo: '2 phút trước',
    priority: 'critical',
    medicalHistory: ['Tăng huyết áp vô căn (4 năm)'],
    allergies: ['Không có'],
    lastSnippet: 'Chào bác sĩ, từ lúc 7h30 sáng nay tôi bắt đầu thấy đè ép, nặng ngực trái, cảm giác như có vật nặng đè ép, hơi nhói lan ra bả vai...',
    vitals: {
      bloodPressure: '135/85',
      bloodPressureStatus: 'Cao',
      heartRate: 88,
      spO2: 97,
      spO2Status: 'Ổn định',
      ecgLead: 'Điện tim nhịp xoang (Lead II Preview)',
      ecgStatus: 'Nghi ngờ ST chênh',
    },
    triage: {
      confidence: 96.8,
      differentialDiagnosis: 'Hội chứng vành cấp (ACS) / Đau thắt ngực không ổn định',
      riskFactors: ['Nam > 45t', 'Tiền sử THA', 'Đau ngực lan tay', 'Vã mồ hôi'],
    },
    protocols: [
      {
        id: 'proto-1',
        label: '1. Điều hướng xe cấp cứu chuyển viện tới Phòng Can thiệp Mạch',
        checked: true,
      },
      {
        id: 'proto-2',
        label: '2. Kích hoạt báo động đỏ khoa Cấp cứu & Tim mạch',
        checked: true,
      },
      {
        id: 'proto-3',
        label: '3. Giữ đường truyền điện thoại liên tục với vợ bệnh nhân',
        checked: false,
      },
    ],
    messages: [
      {
        id: 'msg-1',
        sender: 'patient',
        senderName: 'Vũ Thành Long (Bệnh nhân)',
        time: '08:42',
        content:
          'Chào bác sĩ, từ lúc 7h30 sáng nay tôi bắt đầu thấy đè ép, nặng ngực trái, cảm giác như có vật nặng đè ép, hơi nhói lan ra bả vai và mặt trong cánh tay trái. Kèm theo thấy người vã mồ hôi lạnh, hơi khó thở.',
      },
      {
        id: 'msg-2',
        sender: 'ai',
        senderName: 'VCare+ (MedPaLM Clinical Engine)',
        time: '08:42:15',
        badge: 'Tự động sàng lọc',
        content:
          'Chào anh Long, các triệu chứng đau tức nặng ngực trái đè ép, lan ra cánh tay trái kèm vã mồ hôi và khó thở ở người có tiền sử Tăng huyết áp là dấu hiệu CẢNH BÁO NGUY CƠ CAO của hội chứng mạch vành cấp.',
        alertBox: {
          type: 'critical',
          title: 'Hành động khuyến cáo tức thời:',
          description:
            'Anh Long vui lòng ngồi yên tĩnh hoặc nằm nghỉ ngơi đầu cao 30 độ, giữ bình oxy lưu thông, không tự lái xe hoặc vận động gắng sức. Điều phối viên bác sĩ đang kích hoạt hỗ trợ khẩn cấp.',
        },
      },
    ],
  },
  {
    id: 'p-9104',
    code: 'BN-2024-9104',
    name: 'Nguyễn Thị Hằng',
    age: 31,
    gender: 'Nữ',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150',
    riskLevel: 'TRUNG BÌNH',
    status: 'need_takeover',
    timeAgo: '8 phút trước',
    priority: 'high',
    medicalHistory: ['Sinh mổ con thứ hai (3 tháng)'],
    allergies: ['Dị ứng Aspirin'],
    categoryTag: 'HỎI TƯƠNG TÁC THUỐC (PARACETAMOL CHO CON BÚ)',
    lastSnippet: 'Em đang nuôi con nhỏ 3 tháng tuổi thì có được uống Paracetamol 500mg hạ sốt không ạ? AI gợi ý liều...',
    subStatus: 'Chờ Dược sĩ ký điện tử',
    confidence: 94,
    vitals: {
      bloodPressure: '115/75',
      bloodPressureStatus: 'Bình thường',
      heartRate: 76,
      spO2: 99,
      spO2Status: 'Tốt',
      ecgLead: 'Điện tim bình thường',
      ecgStatus: 'Nhịp xoang đều',
    },
    triage: {
      confidence: 94.0,
      differentialDiagnosis: 'Tư vấn dùng thuốc giảm đau hạ sốt phụ nữ cho con bú',
      riskFactors: ['Đang cho con bú', 'Tiền sử dị ứng NSAIDs/Aspirin'],
    },
    protocols: [
      { id: 'proto-h1', label: '1. Duyệt phác đồ Paracetamol 500mg mỗi 6h khi sốt > 38.5C', checked: true },
      { id: 'proto-h2', label: '2. Lưu ý chống chỉ định phối hợp các chế phẩm có chứa Aspirin', checked: true },
    ],
    messages: [
      {
        id: 'msg-h1',
        sender: 'patient',
        senderName: 'Nguyễn Thị Hằng',
        time: '08:35',
        content: 'Em đang nuôi con nhỏ 3 tháng tuổi thì có được uống Paracetamol 500mg hạ sốt không ạ? AI gợi ý liều dùng nhưng em muốn bác sĩ xác nhận.',
      },
    ],
  },
  {
    id: 'p-4412',
    code: 'BN-2024-4412',
    name: 'Đỗ Văn Minh',
    age: 65,
    gender: 'Nam',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150',
    riskLevel: 'TRUNG BÌNH',
    status: 'need_takeover',
    timeAgo: '15 phút trước',
    priority: 'high',
    medicalHistory: ['Thoái hóa khớp gối', 'Cận thị nặng'],
    allergies: ['Không rõ'],
    categoryTag: 'YÊU CẦU GẶP TRỰC TIẾP NHÂN VIÊN Y TẾ',
    lastSnippet: 'Tôi mắt kém không bấm được nút chọn bác sĩ trên màn hình điện thoại, cho tôi nói chuyện với cô y tá hay...',
    subStatus: 'Chờ tiếp nhận',
    confidence: 61,
    vitals: {
      bloodPressure: '128/82',
      bloodPressureStatus: 'Bình thường',
      heartRate: 80,
      spO2: 98,
      spO2Status: 'Ổn định',
      ecgLead: 'Điện tim xoang',
      ecgStatus: 'Chưa ghi nhận bất thường',
    },
    triage: {
      confidence: 61.2,
      differentialDiagnosis: 'Hỗ trợ đặt lịch hẹn trực tiếp cho bệnh nhân cao tuổi',
      riskFactors: ['Người cao tuổi', 'Hạn chế thị lực'],
    },
    protocols: [
      { id: 'proto-m1', label: '1. Gọi điện trực tiếp thoại hỗ trợ đặt lịch', checked: true },
      { id: 'proto-m2', label: '2. Xếp lịch khám chuyên khoa Cơ Xương Khớp', checked: false },
    ],
    messages: [
      {
        id: 'msg-m1',
        sender: 'patient',
        senderName: 'Đỗ Văn Minh',
        time: '08:28',
        content: 'Tôi mắt kém không bấm được nút chọn bác sĩ trên màn hình điện thoại, cho tôi nói chuyện với cô y tá hay bác sĩ qua điện thoại được không?',
      },
    ],
  },
  {
    id: 'p-5201',
    code: 'BN-2024-5201',
    name: 'Phạm Thúy Mai',
    age: 52,
    gender: 'Nữ',
    avatar: '',
    riskLevel: 'CAO',
    status: 'need_takeover',
    timeAgo: '22 phút trước',
    priority: 'high',
    medicalHistory: ['Đái tháo đường Type 2 (6 năm)', 'Rối loạn mỡ máu'],
    allergies: ['Không có'],
    lastSnippet: 'Chỉ số đường huyết đo lúc sáng là 13.8 mmol/L, có cảm giác khát nước nhiều và mệt mỏi rũ rượi...',
    subStatus: 'Chờ chuyên khoa Nội tiết',
    confidence: 88,
    vitals: {
      bloodPressure: '140/90',
      bloodPressureStatus: 'Tăng nhẹ',
      heartRate: 92,
      spO2: 98,
      spO2Status: 'Ổn định',
      ecgLead: 'Nhịp tim xoang nhanh nhẹ',
      ecgStatus: 'Chưa thấy thiếu máu cục bộ',
    },
    triage: {
      confidence: 88.5,
      differentialDiagnosis: 'Tăng đường huyết cấp tính / Cần điều chỉnh liều Insulin',
      riskFactors: ['Glucose đói > 13 mmol/L', 'Mệt mỏi toàn thân', 'Tiền sử ĐTĐ Type 2'],
    },
    protocols: [
      { id: 'proto-t1', label: '1. Đề xuất xét nghiệm HbA1c và kiểm tra ceton niệu', checked: true },
      { id: 'proto-t2', label: '2. Hội chẩn nhanh với BS Chuyên khoa Nội tiết', checked: false },
    ],
    messages: [
      {
        id: 'msg-t1',
        sender: 'patient',
        senderName: 'Phạm Thúy Mai',
        time: '08:20',
        content: 'Chỉ số đường huyết đo lúc sáng là 13.8 mmol/L, có cảm giác khát nước nhiều và mệt mỏi rũ rượi, tôi có cần tăng liều thuốc đang uống không?',
      },
    ],
  },
];
