import { KPICardData, UrgentCaseItem, OnDutyDoctor, AuditLogItem, HourlyTrafficBar } from './types';

export const MOCK_KPIS: KPICardData[] = [
  {
    id: 'kpi-appointments',
    title: 'Chờ duyệt lịch hẹn',
    value: 18,
    unit: 'yêu cầu',
    trendText: '↑ +4 mới (10p qua)',
    actionText: 'Mở Queue →',
    actionLink: '/staff/queue',
    variant: 'normal',
  },
  {
    id: 'kpi-emergency',
    title: 'CẤP CỨU / KHẨN CẤP •',
    value: '03',
    unit: 'Triage 1 & 2',
    trendText: 'Can thiệp ngay lập tức',
    actionText: 'Xử lý →',
    actionLink: '/staff/queue',
    variant: 'critical',
  },
  {
    id: 'kpi-chat',
    title: 'Hội thoại AI cần can thiệp',
    value: '07',
    unit: 'phiên chat',
    trendText: 'Độ tin cậy < 75%',
    actionText: 'Tiếp quản →',
    actionLink: '/staff/chat',
    variant: 'warning',
  },
  {
    id: 'kpi-confirmed',
    title: 'Lịch khám xác nhận hôm nay',
    value: 142,
    unit: 'lượt khám',
    trendText: 'Tự động AI: 88.5%',
    actionText: 'Duyệt TB: 3.2 ph',
    actionLink: '/staff/doctor-schedule',
    variant: 'success',
  },
];

export const MOCK_URGENT_CASES: UrgentCaseItem[] = [
  {
    id: 'urg-1',
    patientName: 'Trần Văn Hùng',
    age: 58,
    gender: 'Nam',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150',
    priorityBadge: 'KHẨN CẤP / TRIAGE 1',
    priorityType: 'critical',
    alertText: 'Cảnh báo: Đau thắt ngực dữ dội lan ra cánh tay trái, SpO2 93%, nhịp tim 112 bpm',
    sourceText: 'Nguồn AI: Triage bot vừa nhận diện nguy cơ nhồi máu cơ tim cấp • 3 phút trước',
    actionLabel: 'Nhận xử lý Escalation',
    actionLink: '/staff/queue',
    actionType: 'escalate',
  },
  {
    id: 'urg-2',
    patientName: 'Lê Thị Mai',
    age: 34,
    gender: 'Nữ',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150',
    priorityBadge: 'CẢNH BÁO LÂM SÀNG',
    priorityType: 'clinical_warning',
    alertText: 'Đặt khám Tim Mạch nhưng có tiền sử sốc phản vệ Penicillin & Cephalosporin',
    sourceText: 'AI Agent đề xuất: Cần bác sĩ chỉ định thêm phác đồ kháng sinh an toàn • 8 phút trước',
    actionLabel: 'Duyệt & Ghi chú',
    actionLink: '/staff/appointments/approve/MED-8942-VN',
    actionType: 'approve',
  },
  {
    id: 'urg-3',
    patientName: 'Hoàng Minh Đức',
    age: 45,
    gender: 'Nam',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150',
    priorityBadge: 'AI CONFIDENCE 61%',
    priorityType: 'low_confidence',
    alertText: 'AI không đủ độ tin cậy phân biệt giữa trào ngược dạ dày thực quản & cơn đau co thắt mạch vành',
    sourceText: 'Bệnh nhân đang trực tiếp trò chuyện trên cổng MediCare App • 12 phút trước',
    actionLabel: 'Tiếp quản Chat',
    actionLink: '/staff/chat',
    actionType: 'takeover',
  },
  {
    id: 'urg-4',
    patientName: 'Vũ Thị Lan',
    age: 62,
    gender: 'Nữ',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=150',
    priorityBadge: 'ĐỔI LỊCH KHÁM',
    priorityType: 'reschedule',
    alertText: 'Huyết áp đo tại nhà 170/95 mmHg, yêu cầu đổi sang khám sớm ngay trong sáng nay',
    sourceText: 'Lịch ban đầu: 16:30 chiều nay • Đang ưu tiên slot 09:15 P.102',
    actionLabel: 'Xếp lại lịch',
    actionLink: '/staff/doctor-schedule',
    actionType: 'reschedule',
  },
];

export const MOCK_ON_DUTY_DOCTORS: OnDutyDoctor[] = [
  {
    id: 'doc-1',
    name: 'BS.CKII Lê Hoàng Nam',
    title: 'Bác sĩ chuyên khoa II',
    specialty: 'Tim Mạch',
    room: 'Phòng 304',
    waitingCount: 2,
    status: 'Đang khám',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=150',
  },
  {
    id: 'doc-2',
    name: 'BS.CKI Trần Minh Thảo',
    title: 'Bác sĩ chuyên khoa I',
    specialty: 'Nội Tổng Quát',
    room: 'Phòng 201',
    waitingCount: 4,
    status: 'Đang khám',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=150',
  },
  {
    id: 'doc-3',
    name: 'ThS.BS Vũ Thu Trang',
    title: 'Thạc sĩ Bác sĩ',
    specialty: 'Hô Hấp & Nhi',
    room: 'Phòng 105',
    waitingCount: 1,
    status: 'Sẵn sàng',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=150',
  },
];

export const MOCK_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'aud-1',
    time: '08:42',
    actor: 'BS. Nguyễn Phương Linh',
    action: 'Duyệt lịch hẹn ưu tiên ca Tim Mạch #MED-8942 (BN Đặng Hải)',
    highlightCode: '#MED-8942',
  },
  {
    id: 'aud-2',
    time: '08:35',
    actor: 'ĐPV Hoàng Nam',
    action: 'Kích hoạt chuyển viện khẩn cấp 115 cho ca ngất xỉu tiền sảnh',
    isCritical: true,
  },
  {
    id: 'aud-3',
    time: '08:21',
    actor: 'BS. Vũ Thu Trang',
    action: 'Chỉnh sửa phác đồ tư vấn tự động: Bổ sung chỉ định xét nghiệm cúm A/B',
  },
  {
    id: 'aud-4',
    time: '08:05',
    actor: 'Hệ thống AI Core',
    action: 'Tự động tối ưu 38 lịch hẹn ca sáng theo định tuyến khoảng cách phòng khám',
  },
];

export const MOCK_HOURLY_TRAFFIC: HourlyTrafficBar[] = [
  { hour: '07:00', aiHandledPercent: 88.5, hitlHandledPercent: 11.5, aiHeightPercent: 42, hitlHeightPercent: 16 },
  { hour: '08:00', aiHandledPercent: 88.5, hitlHandledPercent: 11.5, aiHeightPercent: 85, hitlHeightPercent: 24 },
  { hour: '09:00 (Hiện tại)', aiHandledPercent: 88.5, hitlHandledPercent: 11.5, aiHeightPercent: 70, hitlHeightPercent: 22, isCurrent: true },
  { hour: '10:00', aiHandledPercent: 88.5, hitlHandledPercent: 11.5, aiHeightPercent: 62, hitlHeightPercent: 18 },
  { hour: '11:00', aiHandledPercent: 88.5, hitlHandledPercent: 11.5, aiHeightPercent: 45, hitlHeightPercent: 12 },
  { hour: '12:00', aiHandledPercent: 88.5, hitlHandledPercent: 11.5, aiHeightPercent: 75, hitlHeightPercent: 20, isProjected: true },
  { hour: '13:00', aiHandledPercent: 88.5, hitlHandledPercent: 11.5, aiHeightPercent: 55, hitlHeightPercent: 15, isProjected: true },
];
